DROP DATABASE IF EXISTS fintest;
CREATE DATABASE fintest CHARACTER SET utf8 COLLATE utf8_general_ci;
USE fintest;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) COMMENT 'User name',
  login VARCHAR(255) COMMENT 'User login',
  psw VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;

INSERT INTO `users` (`name`, `login`, `psw`) VALUES ('Test', 'test@test.test','$2y$10$ZdxXdjNZGd7CJNV5KdgJjOnEnVGTD5X21uEjgtG4qiom.22iYB6eG');

DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  user_id BIGINT UNSIGNED,
  value DECIMAL(14,2),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`)
        REFERENCES `users` (`id`)
        ON UPDATE RESTRICT ON DELETE RESTRICT 
) ENGINE=INNODB;


